version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build
      - run:
          name: Build the Docker image
          command: |
            docker build -t my-app .
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-dependencies-{{ epoch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: docker/compose:1.29.1
      - image: docker:20.10.8-dind
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Start Docker daemon
          command: dockerd-entrypoint.sh &
      - run:
          name: Install Docker Compose
          command: apk add --no-cache py-pip && pip install docker-compose
      - run:
          name: Deploy the app
          command: |
            docker-compose up -d
      - run:
          name: Deploy to VPS
          command: |
             ssh -oStrictHostKeyChecking=no root@144.91.104.7 "cd /usr/projects/Circle-CI && sh -x deploy.sh"    
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main