version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build
          command: npm run build

      - run:
          name: Build Docker Image
          command: |
            docker build -t phianhdev/react-docker:lastest .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker push phianhdev/react-docker:lastest

  deploy:
    docker:
      - image: docker:19.03.13

    steps:
      - checkout

      - setup_remote_docker
      
      - run:
          name: Deploy
          command: |
            ssh -oStrictHostKeyChecking=no root@144.91.104.7 "cd /usr/projects/Circle-CI && sh -x deploy.sh"   
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main